name: Testing

on:
    workflow_dispatch:
     inputs:
        tgt_env:
            description: Enviornment
            required: true
            type: environment
        action:
            description: Action
            options:
                - create
                - create and Copy 1
                - create and copy 2
            type: choice
        logLevel:
            description: 'Log level'

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run: 
                echo "This is NOT working or not "